#!/usr/bin/env bash

echo "mysql username:"
read "uid"

echo "mysql password:"
read "passwd"

mysql -u "${uid}" -p"${passwd}" -e "SELECT TABLE_SCHEMA, TABLE_NAME FROM information_schema.TABLES WHERE ENGINE='MyISAM';"
